/*
 * Frame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui;

import com.date.*;

import java.util.regex.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  __USER__
 */
public class Frame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Frame */
	public Frame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings("serial")
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u8f93\u5165\u5f53\u524d\u65e5\u671f\uff1a");

		jLabel2.setText("\u683c\u5f0f\uff1aYYYY/MM/DD");

		jButton1.setText("\u8ba1\u7b97\u65e5\u671f");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "公历", "星期", "农历", "生肖年" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														405, Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		150,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel2,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		161,
																		Short.MAX_VALUE))
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.LEADING))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						23,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton1))
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										166, Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String date = jTextField1.getText();
		if (date.equals(""))
			JOptionPane.showMessageDialog(jScrollPane1, "请输入当前日期", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		//System.out.println(date);
		else {
			Pattern pattern = Pattern.compile("^((\\d{2}"
					+ "(([02468][048])|([13579][26]))[\\-\\/\\s]"
					+ "?((((0?[13578])|(1[02]))[\\-\\/\\s]?((0?"
					+ "[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])"
					+ "|(11))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9]"
					+ ")|(30)))|(0?2[\\-\\/\\s]?((0?[1-9])|([1-2"
					+ "][0-9])))))|(\\d{2}(([02468][1235679])|("
					+ "[13579][01345789]))[\\-\\/\\s]?((((0?[13578"
					+ "])|(1[02]))[\\-\\/\\s]?((0?[1-9])|([1-2][0-9"
					+ "])|(3[01])))|(((0?[469])|(11))[\\-\\/\\s]?"
					+ "((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-\\/\\s]"
					+ "?((0?[1-9])|(1[0-9])|(2[0-8]))))))(\\s(((0?[0-9]"
					+ ")|([1-2][0-3]))\\:([0-5]?[0-9])((\\s)|(\\:"
					+ "([0-5]?[0-9])))))?$");
			Matcher matcher = pattern.matcher(date);
			if (!matcher.matches()) {
				JOptionPane.showMessageDialog(jScrollPane1, "请输入正确日期", "ERROR",
						JOptionPane.ERROR_MESSAGE);
			} else {
				//System.out.println(date);
				DefaultTableModel tableModel1 = (DefaultTableModel) jTable1
						.getModel();
				tableModel1.setRowCount(0);
				jTable1.invalidate();
				DateAnalyse dateAnalyse = new DateAnalyse(date, jTable1);
				dateAnalyse.Analyse();
			}
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}